displayName: Traefik Tokenizer
summary: ä¸€ä¸ªç”¨äº Traefik çš„ Token è®°å½•æ’ä»¶ï¼Œç”¨äºæ•è·è¯·æ±‚/å“åº”å¹¶ä¸ŠæŠ¥è‡³å¤–éƒ¨ APIã€‚
testData:
  api_url: http://localhost:8000/log

author: æ¯›å·³ç…œ
license: MIT
type: middleware
# ğŸ‘‡ğŸ‘‡ğŸ‘‡ è¿™ä¸ªå­—æ®µï¼ˆéå¸¸é‡è¦ï¼ï¼ï¼ï¼‰
module: llmtoken
